data:
  batch_size: 256
  color_jitter_strength: 0.0
  image_folder: /content/drive/MyDrive/Data/Dataset_normalized.h5
  num_workers: 2
  pin_mem: true
  root_path: /content/drive/MyDrive/Data/Dataset_normalized.h5
  use_color_distortion: false
  use_gaussian_blur: true
  statistics_path: /content/drive/MyDrive/Data/after_outlier_mean_std_record_dataset.json
  use_horizontal_flip: True
  use_vertical_flip: true
  use_rotation: true  
logging:
  folder: /content/drive/MyDrive/Logging/resnet_base
  write_tag: barlow_gsoc
meta:
  load_checkpoint: false
  model_name: Resnet
  resnet_blocks: 2-4-6-3
  resnet_strides: 1-2-2-2
  resnet_planes: 16-32-64-128
  mlp_size: 2048-2048-512
  lamb: 0.01
  read_checkpoint: barlow_gsoc-ep4.pth.tar
  use_bfloat16: true
optimization:
  epochs: 30
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0001
  warmup: 1
  weight_decay: 0.04
